services:
 

#  pgadmin:
#    container_name: pgadmin4
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: root
#    ports:
#      - "5050:80"

 my_fastapi:
    build:
     # We are using the created dockerfile
      dockerfile: dockerfile-fastapi
     # We are using ports 8000 both on host and on the server
    ports:
      - "8000:8000"
     # Mounting our Current Working Directory to the
    volumes:
      - ".:${CWD:-/code}"

# volumes:
#  postgres-db: